interfaces:
  - name: Ethernet1
    description: leaf-1
    ipv4_address: 10.0.100.2/24
    mode: l3_ipv4
  - name: Ethernet2
    description: spine-1
    ipv4_address: 10.0.2.2/24
    mode: l3_ipv4
  - name: Ethernet3
    description: spine-2
    ipv4_address: 10.2.0.2/24
    mode: l3_ipv4
